apiVersion: v1
kind: Service
metadata:
  name: db-connection-service
  namespace: db-connection
  labels:
    service: db-connection-service
spec:
  type: LoadBalancer
  selector:
    service: db-connection-service
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000